language: node_js
node_js:
- '12.22.10'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=digitick)
  - secure: OrTok8XVivPYJV+FiGDDFunKiADr/jShIZgIqWwWA7xfgpLM7o7gvCJM7tHKxpWLMxUH4KuO47oPb1hJ4A3pSVxjIjHWM5NnkAXi5rzUnsFRuUvCcn9BIxtD82bzGOV/yVWmknt0/0kMGR5J4ZT+vze+v2AlUPJXcH8+s1CmMXi90UWVUvzA8/uLskKSUHwNNpHt/8dKClf1fNOTyxVPfFSJN0mYYGBTFvzI0zt4LBwMQ3d7NvlANek7xGRfPxl3TI6W4DFV7JsBR1lrHzj3S+hLgCKT60vBpjyfPnDeYv2SlfcN51XfRGUFAudtq1UtYvYJbfYNg2d1pZejAnfqQSy6bQIccfcN3huXef1D9Enrh1OXJTw659kULCuWrL4Z1veDacuv6gydi151b2TSrkmtNkUVW3kX9PK0m7LfkFu+VzvLjFGk5qciU2f4xSh1FGkEhYj3+RjcJiMqB63PvXvQJWSsNQlWB/1Y7tdRoqHyedQL7N4Qh//+0yW7OFj91I+lMgmvnugO8Ebrt/I3ZUdTRX87nUpMwFRc2rGghPPI3tyaK+RSxcGMF0UM9MGi/9UEgkPHhu61Ks56AxIZlfrlKbFPNapwhM6wykMTku/L5k+TPrfPoxM/whP5JAn9lUfw8Z8Tp43YIre5YUh8NjOeFrOCl/0Ne2TMQImBYu4=
  # MATTERMOST_HOOK_URL
  - secure: XvEev4llzk7w+y3rVYo4v56HpGCzFNAGI0RxaeyBWB0j2+2EQSP7ByCPufR8Rq1dEfIxUGMW6PoNBpojkAoDvvjh9N5tpPMhznlRTf1fUJsj6/nq9Sv5vp6oVq3qvCNYFn/N3filieKz22QOYrZOd2iyCgrciBMBFj6CNMN2YuY0A4RqKH0BL6NSda5cDE6iCQIVFg4UNTZYlvwS+smOj6qTHlU34P958bshgx1tXS4MyH9WcVex1zID9nOyFZ4z2eFv272vbOBWZmwe9xiywqKZPexoGHQsDpH+iwGAyRpc6PrNEurfO+WaRQQ4Ycwf5K9C3wfFwIUGFfm7bKKyF/a6Q7C/k1naz4Wcwpws9vqAFGyNcWqRKo6PLSCVf7qPBM46n4AG1cd6oM1NjJRiFuigx9FAiRrI0VW7W1y/FHwJB28p38OsYeDS5skegno/MBQms9LBqQn3n0foWjdbQV0yErVMRYIuNBpYLlUWgV1VmAhqC7LozN7NAOPZWq4pYGUOfBz+4omC94zbI3K5g9lxs4fjRyoF3RGTw9cP9U0srdAM3ku43zbJVwsXY/+6Kk/ofFr+euUjtTJ8lnubSUaTtryjMW+oap8PFySzLH/Gsl6AenE8RPOWowrgD1bhUZ5IJe9Smoy3pFThflHTEO6E+hbxM2NRH9Btc8KnLeU=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_da9dac2ea8e4_key -iv $encrypted_da9dac2ea8e4_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
